### PR TITLE
Resolve problem with passing experimental options to Chrome Driver

### PR DESCRIPTION
**Pull request by stevenebutler**
This patch resolves a problem with passing experimental options to Chrome Driver that are nested inside a JSON object.

This was particularly a problem when trying to pass deviceEmulation
properties.  The JSON object was not being serialized in the correct
format.

With this fix, Chrome webdriver can be made to emulate a mobile chrome
browser when the following JSON is used to pass experimental options to
chrome webdriver:

{ 
	"mobileEmulation": 
	{
		"deviceName": "Google Nexus 5"
	}
}

### CODE REVIEW

**Comment by vmi** [comment]
Hi,

Thanks your PR, but I will replace JSON library from org.json to com.google.code.gson (now working).
Please wait.

**Comment by stevenebutler** [comment]
No problem. I considered same, but went for minimal change to get it
working.  I thought it odd that the JSON object didn't serialize out the
same as it came in with that library.

On 3 February 2016 at 09:07, Motonori IWAMURO <notifications@github.com>
wrote:

> Hi,
>
> Thanks your PR, but I will replace JSON library from org.json to
> com.google.code.gson (now working).
> Please wait.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vmi/selenese-runner-java/pull/184#issuecomment-178877502>
> .
>



-- 
Regards,
Steven Butler

**Comment by vmi** [comment]
I replaced JSON library from org.json to com.google.code.gson.
But I don't test for this problem yet.
Please test it.

**Comment by stevenebutler** [comment]
I will try to have a look soon.  I have been in other things lately.

**Comment by stevenebutler** [comment]
I have tested current trunk with experimental options and it appears to
work fine with doing mobile chrome simulation, which was my use case.

On 11 February 2016 at 14:12, Steven Butler <sebutler@gmail.com> wrote:

> I will try to have a look soon.  I have been in other things lately.
> On 9 Feb 2016 8:29 am, "Motonori IWAMURO" <notifications@github.com>
> wrote:
>
>> I replaced JSON library from org.json to com.google.code.gson.
>> But I don't test for this problem yet.
>> Please test it.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/vmi/selenese-runner-java/pull/184#issuecomment-181595222>
>> .
>>
>


-- 
Regards,
Steven Butler

**Comment by vmi** [comment]
Thanks.
I released new version with the fix.

**Pull request closed without merging**
