### PR TITLE
Add "--max-time" option,  Limit the time the whole operation is allowed to take.

### PR DESCRIPTION
**Pull request by koichirok**
This pull request add "--max-time" option, limit the time for selenese-runner's entire operation.

To save HTML/XML result, this PR doesn't shutdown operation immediately, only interrupts current operation and makes result of current command failure when the time specified by "--max-time" is reached.

This PR also replace use of commons httpcomponents' httpclient in selenium-remote-driver with httpasyncclient so that we can interrupt operation immediately.

Since httpclient do blocking read, we couldn't interrupt the operation especially waiting data from server socket.
It becomes a problem when communicate with quite slow response web server, could not interrupt operation several seconds or more.

### CODE REVIEW

**Comment by koichirok** [comment]
oops, I'll fix failed test.

**Comment by koichirok** [comment]
I've fixed failed test.

**Comment by vmi** [comment]
Thanks for your PR!

But I think it's overkill to use AspectJ to replace `ApacheHttpClient.Factory#createClient(URL)`, and it influences existing features more than necessary.

I changed your PR as follows.

https://github.com/vmi/selenese-runner-java/tree/max-time-support-without-aspectj

If the change doesn't obstruct your purpose, I will merge this.

**Comment by koichirok** [comment]
> But I think it's overkill to use AspectJ to replace ApacheHttpClient.Factory#createClient(URL), and it influences existing features more than necessary.

I agree.

Your version works fine too, and I prefer your version :)

Please merge your version. 

Regards.

**Pull request merged**
