### PR TITLE
make waitFor* commands timeout rigid

### PR DESCRIPTION
**Pull request by uchida**
In `selenese-runner-java`, `waitFor*` command try assertions time and time again until reaching timeout.
However, `selenese-runner-java` does not check timeout on first assertion trial even if it reaches timeout.

This pull request fix this problem.

This changes will break some slow tests, for example following is a part of [selenese-runner failed tests on travis](https://travis-ci.org/uchida/selenese-runner-java/builds/111706879).

<pre>
...
Tests run: 50, Failures: 6, Errors: 0, Skipped: 17, Time elapsed: 426.659 sec <<< FAILURE! - in jp.vmi.selenium.selenese.DriverDependentTest
issue114[0: htmlunit](jp.vmi.selenium.selenese.DriverDependentTest)  Time elapsed: 31.138 sec  <<< FAILURE!
java.lang.AssertionError: 
Expected: is an instance of jp.vmi.selenium.selenese.result.Success
     but: <[Warning: Timed out after 30000ms]> is a jp.vmi.selenium.selenese.result.Warning
	at jp.vmi.selenium.selenese.DriverDependentTest.issue114(DriverDependentTest.java:326)
iframe[1: phantomjs](jp.vmi.selenium.selenese.DriverDependentTest)  Time elapsed: 49.205 sec  <<< FAILURE!
java.lang.AssertionError: 
Expected: is an instance of jp.vmi.selenium.selenese.result.Success
     but: <[Warning: Timed out after 30000ms]> is a jp.vmi.selenium.selenese.result.Warning
	at jp.vmi.selenium.selenese.DriverDependentTest.iframe(DriverDependentTest.java:146)
rollup[1: phantomjs](jp.vmi.selenium.selenese.DriverDependentTest)  Time elapsed: 63.811 sec  <<< FAILURE!
java.lang.AssertionError: 
Expected: is an instance of jp.vmi.selenium.selenese.result.Success
     but: <[Warning: Timed out after 30000ms]> is a jp.vmi.selenium.selenese.result.Warning
	at jp.vmi.selenium.selenese.DriverDependentTest.rollup(DriverDependentTest.java:168)
locator[1: phantomjs](jp.vmi.selenium.selenese.DriverDependentTest)  Time elapsed: 41.625 sec  <<< FAILURE!
java.lang.AssertionError: 
Expected: is an instance of jp.vmi.selenium.selenese.result.Success
     but: <[Warning: Timed out after 30000ms]> is a jp.vmi.selenium.selenese.result.Warning
	at jp.vmi.selenium.selenese.DriverDependentTest.locator(DriverDependentTest.java:138)
issue114[1: phantomjs](jp.vmi.selenium.selenese.DriverDependentTest)  Time elapsed: 47.538 sec  <<< FAILURE!
java.lang.AssertionError: 
Expected: is an instance of jp.vmi.selenium.selenese.result.Success
     but: <[Warning: Timed out after 30000ms]> is a jp.vmi.selenium.selenese.result.Warning
	at jp.vmi.selenium.selenese.DriverDependentTest.issue114(DriverDependentTest.java:326)
issue179[1: phantomjs](jp.vmi.selenium.selenese.DriverDependentTest)  Time elapsed: 67.069 sec  <<< FAILURE!
java.lang.AssertionError: 
Expected: is an instance of jp.vmi.selenium.selenese.result.Success
     but: <[Warning: Timed out after 30000ms]> is a jp.vmi.selenium.selenese.result.Warning
	at jp.vmi.selenium.selenese.DriverDependentTest.issue179(DriverDependentTest.java:340)
...
Results :
Failed tests: 
  DriverDependentTest.iframe:146 
Expected: is an instance of jp.vmi.selenium.selenese.result.Success
     but: <[Warning: Timed out after 30000ms]> is a jp.vmi.selenium.selenese.result.Warning
  DriverDependentTest.issue114:326 
Expected: is an instance of jp.vmi.selenium.selenese.result.Success
     but: <[Warning: Timed out after 30000ms]> is a jp.vmi.selenium.selenese.result.Warning
  DriverDependentTest.issue114:326 
Expected: is an instance of jp.vmi.selenium.selenese.result.Success
     but: <[Warning: Timed out after 30000ms]> is a jp.vmi.selenium.selenese.result.Warning
  DriverDependentTest.issue179:340 
Expected: is an instance of jp.vmi.selenium.selenese.result.Success
     but: <[Warning: Timed out after 30000ms]> is a jp.vmi.selenium.selenese.result.Warning
  DriverDependentTest.locator:138 
Expected: is an instance of jp.vmi.selenium.selenese.result.Success
     but: <[Warning: Timed out after 30000ms]> is a jp.vmi.selenium.selenese.result.Warning
  DriverDependentTest.rollup:168 
Expected: is an instance of jp.vmi.selenium.selenese.result.Success
     but: <[Warning: Timed out after 30000ms]> is a jp.vmi.selenium.selenese.result.Warning
Tests run: 188, Failures: 6, Errors: 0, Skipped: 21
</pre>

### CODE REVIEW

**Comment by uchida** [comment]
To note about implementation in eb30ef4, [`java.util.concurrent.FutureTask`](https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/FutureTask.html) is used for timeout and [java.util.concurrent.atomic.AtomicReference](https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/atomic/AtomicReference.html) is used to keep last status used when `TimeoutException` is raised.

However [com.google.common.util.concurrent.TimeLimiter](http://docs.guava-libraries.googlecode.com/git/javadoc/com/google/common/util/concurrent/TimeLimiter.html) also would be an option to implement timeout.
In this case, proxied object of `TimeLimiter` could keep last status without `AtomicReference`.

**Comment by uchida** [comment]
and in eb30ef4 replacing `AtomicReference<String>` to reference of String could be done because one one could modify it without argument of `FutureTask`.
The reason for using `AtomicReference` is just a precaution.

**Comment by vmi** [comment]
Hi,

Thanks for your PR.
But your changes cause test failures. (A result of JUnit test on Eclipse was 16 failures)
It seems to have broken waitFor* commands.

```
java.lang.AssertionError: 
Expected: is an instance of jp.vmi.selenium.selenese.result.Success
     but: <[Warning: Timed out after 30000ms]> is a jp.vmi.selenium.selenese.result.Warning
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at jp.vmi.selenium.selenese.DriverDependentTest.issue114(DriverDependentTest.java:326)
(snip)
```

```
[2016-03-01 07:38:20.440] [main] j.v.s.s.inject.CommandLogInterceptor [INFO] <13> Command#13: waitForElementPresent("id=text")
[2016-03-01 07:38:50.444] [main] j.v.s.selenese.command.Assertion [WARN] null
[2016-03-01 07:38:50.447] [main] j.v.s.s.inject.CommandLogInterceptor [ERROR] Command#13: waitForElementPresent("id=text") => [Warning: Timed out after 30000ms]
```

**Comment by vmi** [comment]
I think we cannot use concurrent API because it breaks communication with a browser of WebDriver.

**Comment by uchida** [comment]
Sorry for no replying, I agree this pull request break some WebDriver communication, 
I expect that finally calling `DELETE /session/{session id}` will clean WebDriver communication, but screenshots on fail will not work in this way.
And 2a6dcafff641 (fix for #190) may bring some improvement what I want.
So I close this pull request.

**Pull request closed without merging**
